const BRANCH_THEMES = [
  {
    id: "safe",
    label: "Safe Path",
    description: "Predictable progress, lower downside, steady compounding.",
    aiDirective:
      "Design for stability, lower volatility, and realistic short-term cash-flow security.",
  },
  {
    id: "high_income",
    label: "High Income Path",
    description: "Optimized for earning power and upside over comfort.",
    aiDirective:
      "Design for income acceleration and upside, while acknowledging pressure and tradeoffs.",
  },
  {
    id: "meaning",
    label: "Meaning Path",
    description: "Purpose, contribution, and psychological alignment first.",
    aiDirective:
      "Design for purpose, contribution, and values congruence over pure status.",
  },
  {
    id: "creative",
    label: "Creative Path",
    description: "Expression, originality, and autonomy in craft.",
    aiDirective:
      "Design for creative output, portfolio growth, and identity-based work.",
  },
  {
    id: "freedom",
    label: "Freedom Path",
    description: "Flexibility, autonomy, and life-design optionality.",
    aiDirective:
      "Design for autonomy, schedule flexibility, and long-term optionality.",
  },
];

const QUESTION_POOL = [
  {
    id: "age_range",
    category: "demographic",
    module: "core",
    priority: 100,
    kind: "single",
    question: "Which age range best describes you right now?",
    options: [
      { value: "18_24", label: "18-24" },
      { value: "25_34", label: "25-34" },
      { value: "35_44", label: "35-44" },
      { value: "45_54", label: "45-54" },
      { value: "55_plus", label: "55+" },
    ],
  },
  {
    id: "country",
    category: "demographic",
    module: "core",
    priority: 98,
    kind: "text",
    question: "Which country are you currently based in?",
    placeholder: "Type your country",
  },
  {
    id: "education_level",
    category: "demographic",
    module: "core",
    priority: 96,
    kind: "single",
    question: "What is your current education level?",
    options: [
      { value: "high_school", label: "High school" },
      { value: "associate", label: "Associate degree" },
      { value: "bachelor", label: "Bachelor's degree" },
      { value: "master", label: "Master's degree" },
      { value: "doctorate", label: "Doctorate" },
      { value: "self_taught", label: "Mostly self-taught" },
    ],
  },
  {
    id: "income_expectation",
    category: "demographic",
    module: "core",
    priority: 94,
    kind: "single",
    question: "What yearly income would feel acceptable in the next 2-3 years?",
    options: [
      { value: "under_50k", label: "Under $50k" },
      { value: "50_80k", label: "$50k-$80k" },
      { value: "80_120k", label: "$80k-$120k" },
      { value: "120_180k", label: "$120k-$180k" },
      { value: "180_plus", label: "$180k+" },
    ],
  },
  {
    id: "willing_relocate",
    category: "career_reality",
    module: "core",
    priority: 93,
    kind: "single",
    question: "Are you willing to relocate for the right opportunity?",
    options: [
      { value: "yes", label: "Yes" },
      { value: "maybe", label: "Maybe" },
      { value: "no", label: "No" },
    ],
  },
  {
    id: "relocation_radius",
    category: "career_reality",
    module: "core",
    priority: 78,
    kind: "single",
    question: "If relocating, how far would you realistically go?",
    options: [
      { value: "same_city", label: "Within my city" },
      { value: "same_country", label: "Within my country" },
      { value: "international", label: "Internationally" },
    ],
    dependsOn: [{ id: "willing_relocate", values: ["yes", "maybe"] }],
  },
  {
    id: "stable_income_timing",
    category: "career_reality",
    module: "core",
    priority: 92,
    kind: "single",
    question: "How soon do you need stable income from your next direction?",
    options: [
      { value: "urgent", label: "Within 3 months" },
      { value: "soon", label: "Within 6-9 months" },
      { value: "flexible", label: "I can tolerate 12+ months" },
    ],
  },
  {
    id: "financial_runway",
    category: "career_reality",
    module: "core",
    priority: 90,
    kind: "single",
    question: "How much financial runway can you handle for a transition?",
    options: [
      { value: "none", label: "Almost none" },
      { value: "short", label: "1-3 months" },
      { value: "medium", label: "4-9 months" },
      { value: "long", label: "10+ months" },
    ],
  },
  {
    id: "willing_study_again",
    category: "career_reality",
    module: "core",
    priority: 89,
    kind: "single",
    question: "Would you be willing to study again for a new path?",
    options: [
      { value: "yes", label: "Yes" },
      { value: "maybe", label: "Maybe, if practical" },
      { value: "no", label: "No" },
    ],
  },
  {
    id: "study_time_commitment",
    category: "career_reality",
    module: "core",
    priority: 75,
    kind: "single",
    question: "How much study time per week could you sustain?",
    options: [
      { value: "under_5", label: "Under 5 hours" },
      { value: "5_10", label: "5-10 hours" },
      { value: "10_20", label: "10-20 hours" },
      { value: "20_plus", label: "20+ hours" },
    ],
    dependsOn: [{ id: "willing_study_again", values: ["yes", "maybe"] }],
  },
  {
    id: "work_environment",
    category: "career_reality",
    module: "core",
    priority: 88,
    kind: "single",
    question: "What work environment suits you best?",
    options: [
      { value: "remote", label: "Mostly remote" },
      { value: "hybrid", label: "Hybrid" },
      { value: "office", label: "Mostly in-office" },
      { value: "project_based", label: "Project-by-project flexibility" },
    ],
  },
  {
    id: "leadership_preference",
    category: "career_reality",
    module: "core",
    priority: 86,
    kind: "single",
    question: "Do you prefer leadership responsibility or focused solo execution?",
    options: [
      { value: "lead_team", label: "Lead teams" },
      { value: "solo_specialist", label: "Solo specialist" },
      { value: "balanced", label: "A balance of both" },
    ],
  },
  {
    id: "management_energy",
    category: "career_reality",
    module: "core",
    priority: 72,
    kind: "single",
    question: "How much people-management complexity can you tolerate?",
    options: [
      { value: "low", label: "Low" },
      { value: "medium", label: "Medium" },
      { value: "high", label: "High" },
    ],
    dependsOn: [{ id: "leadership_preference", values: ["lead_team", "balanced"] }],
  },
  {
    id: "freedom_vs_stability",
    category: "values",
    module: "core",
    priority: 92,
    kind: "single",
    question: "Which matters more right now: freedom or stability?",
    options: [
      { value: "freedom_strong", label: "Strongly freedom" },
      { value: "freedom_lean", label: "Slightly freedom" },
      { value: "balanced", label: "Balanced" },
      { value: "stability_lean", label: "Slightly stability" },
      { value: "stability_strong", label: "Strongly stability" },
    ],
  },
  {
    id: "prestige_vs_peace",
    category: "values",
    module: "core",
    priority: 88,
    kind: "single",
    question: "Which tradeoff feels more honest for you: prestige or peace?",
    options: [
      { value: "prestige", label: "Prestige" },
      { value: "mostly_prestige", label: "Mostly prestige" },
      { value: "balanced", label: "Balanced" },
      { value: "mostly_peace", label: "Mostly peace" },
      { value: "peace", label: "Peace" },
    ],
  },
  {
    id: "money_vs_meaning",
    category: "values",
    module: "core",
    priority: 90,
    kind: "single",
    question: "In the next chapter, what should dominate: money or meaning?",
    options: [
      { value: "money", label: "Money" },
      { value: "mostly_money", label: "Mostly money" },
      { value: "balanced", label: "Balanced" },
      { value: "mostly_meaning", label: "Mostly meaning" },
      { value: "meaning", label: "Meaning" },
    ],
  },
  {
    id: "risk_vs_certainty",
    category: "values",
    module: "core",
    priority: 87,
    kind: "single",
    question: "Do you want to optimize for risk-taking or certainty?",
    options: [
      { value: "risk", label: "Risk" },
      { value: "mostly_risk", label: "Mostly risk" },
      { value: "balanced", label: "Balanced" },
      { value: "mostly_certainty", label: "Mostly certainty" },
      { value: "certainty", label: "Certainty" },
    ],
    boostIf: [{ id: "stable_income_timing", values: ["urgent", "soon"] }],
  },
  {
    id: "autonomy_importance",
    category: "values",
    module: "core",
    priority: 84,
    kind: "single",
    question: "How important is day-to-day autonomy to your well-being?",
    options: [
      { value: "critical", label: "Critical" },
      { value: "high", label: "High" },
      { value: "medium", label: "Medium" },
      { value: "low", label: "Low" },
    ],
  },
  {
    id: "impact_orientation",
    category: "values",
    module: "core",
    priority: 80,
    kind: "single",
    question: "What is more motivating: visible impact or reliable comfort?",
    options: [
      { value: "impact", label: "Visible impact" },
      { value: "balanced", label: "Balanced" },
      { value: "comfort", label: "Reliable comfort" },
    ],
  },
  {
    id: "intro_extro",
    category: "psychology",
    module: "core",
    priority: 85,
    kind: "single",
    question: "Where do you naturally restore energy?",
    options: [
      { value: "introverted", label: "Solitude and deep focus" },
      { value: "ambivert", label: "A mix" },
      { value: "extroverted", label: "Interaction and momentum" },
    ],
  },
  {
    id: "stress_tolerance",
    category: "psychology",
    module: "core",
    priority: 84,
    kind: "single",
    question: "How much sustained stress can you tolerate before quality drops?",
    options: [
      { value: "low", label: "Low" },
      { value: "medium", label: "Medium" },
      { value: "high", label: "High" },
    ],
  },
  {
    id: "discipline_level",
    category: "psychology",
    module: "core",
    priority: 83,
    kind: "single",
    question: "How consistent are you with long-term self-directed plans?",
    options: [
      { value: "emerging", label: "Inconsistent but improving" },
      { value: "steady", label: "Mostly steady" },
      { value: "high", label: "Very disciplined" },
    ],
  },
  {
    id: "creativity_level",
    category: "psychology",
    module: "core",
    priority: 82,
    kind: "single",
    question: "How central is creativity in the work you want to do?",
    options: [
      { value: "essential", label: "Essential" },
      { value: "important", label: "Important" },
      { value: "supportive", label: "Supportive but not central" },
    ],
  },
  {
    id: "analytical_level",
    category: "psychology",
    module: "core",
    priority: 82,
    kind: "single",
    question: "How much analytical complexity do you enjoy handling?",
    options: [
      { value: "low", label: "Low" },
      { value: "medium", label: "Medium" },
      { value: "high", label: "High" },
    ],
  },
  {
    id: "ambiguity_tolerance",
    category: "psychology",
    module: "core",
    priority: 80,
    kind: "single",
    question: "How comfortable are you making decisions with incomplete information?",
    options: [
      { value: "low", label: "Low" },
      { value: "medium", label: "Medium" },
      { value: "high", label: "High" },
    ],
  },
  {
    id: "daily_routine",
    category: "lifestyle",
    module: "core",
    priority: 83,
    kind: "single",
    question: "Which daily rhythm sounds healthiest for you?",
    options: [
      { value: "structured", label: "Structured routine" },
      { value: "semi_structured", label: "Semi-structured" },
      { value: "fluid", label: "Fluid, changing days" },
    ],
  },
  {
    id: "social_energy",
    category: "lifestyle",
    module: "core",
    priority: 82,
    kind: "single",
    question: "How much social interaction do you want in a typical workday?",
    options: [
      { value: "low", label: "Low" },
      { value: "medium", label: "Medium" },
      { value: "high", label: "High" },
    ],
  },
  {
    id: "pace_preference",
    category: "lifestyle",
    module: "core",
    priority: 81,
    kind: "single",
    question: "Which pace feels sustainable long-term?",
    options: [
      { value: "calm", label: "Calm and steady" },
      { value: "balanced", label: "Balanced challenge" },
      { value: "intense", label: "High-intensity" },
    ],
  },
  {
    id: "travel_tolerance",
    category: "lifestyle",
    module: "core",
    priority: 76,
    kind: "single",
    question: "How much travel would you accept for career growth?",
    options: [
      { value: "none", label: "None" },
      { value: "occasional", label: "Occasional" },
      { value: "frequent", label: "Frequent" },
    ],
  },
  {
    id: "routine_vs_variety",
    category: "lifestyle",
    module: "core",
    priority: 76,
    kind: "single",
    question: "Do you prefer repeating mastery or constant variety?",
    options: [
      { value: "routine", label: "Repeating mastery" },
      { value: "balanced", label: "Balanced" },
      { value: "variety", label: "Constant variety" },
    ],
  },

  // Premium depth module questions
  {
    id: "motivation_profile",
    category: "premium_depth",
    module: "premium",
    priority: 96,
    kind: "single",
    question: "What most reliably moves you into action?",
    options: [
      { value: "mastery", label: "Mastery and growth" },
      { value: "recognition", label: "Recognition and status" },
      { value: "service", label: "Helping others" },
      { value: "independence", label: "Independence" },
    ],
  },
  {
    id: "personality_work_style",
    category: "premium_depth",
    module: "premium",
    priority: 94,
    kind: "single",
    question: "When pressure rises, what is your default style?",
    options: [
      { value: "planner", label: "Plan and structure" },
      { value: "sprinter", label: "Sprint and improvise" },
      { value: "collaborator", label: "Seek alignment with others" },
      { value: "independent", label: "Withdraw and execute solo" },
    ],
  },
  {
    id: "values_conflict",
    category: "premium_depth",
    module: "premium",
    priority: 92,
    kind: "single",
    question: "Which internal conflict shows up most in your decisions?",
    options: [
      { value: "security_vs_growth", label: "Security vs growth" },
      { value: "money_vs_identity", label: "Money vs identity" },
      { value: "autonomy_vs_belonging", label: "Autonomy vs belonging" },
      { value: "impact_vs_comfort", label: "Impact vs comfort" },
    ],
  },
  {
    id: "cognitive_style",
    category: "premium_depth",
    module: "premium",
    priority: 90,
    kind: "single",
    question: "How do you make your best decisions?",
    options: [
      { value: "data_first", label: "Data first" },
      { value: "intuition_first", label: "Intuition first" },
      { value: "dialogue_first", label: "Talking it through" },
      { value: "prototype_first", label: "Trying fast experiments" },
    ],
  },
  {
    id: "failure_response",
    category: "premium_depth",
    module: "premium",
    priority: 88,
    kind: "single",
    question: "After setbacks, which response sounds most like you?",
    options: [
      { value: "recover_fast", label: "Recover quickly" },
      { value: "need_reflection", label: "Need reflection time" },
      { value: "seek_support", label: "Seek support" },
      { value: "avoid_risk", label: "Pull back from risk" },
    ],
  },
  {
    id: "decision_velocity",
    category: "premium_depth",
    module: "premium",
    priority: 86,
    kind: "single",
    question: "How fast do you prefer to commit to major decisions?",
    options: [
      { value: "fast", label: "Fast" },
      { value: "balanced", label: "Balanced" },
      { value: "deliberate", label: "Deliberate" },
    ],
  },
  {
    id: "energy_rhythm",
    category: "premium_depth",
    module: "premium",
    priority: 84,
    kind: "single",
    question: "When is your sharpest cognitive energy usually available?",
    options: [
      { value: "morning", label: "Morning" },
      { value: "afternoon", label: "Afternoon" },
      { value: "evening", label: "Evening" },
      { value: "variable", label: "Variable" },
    ],
  },
  {
    id: "identity_anchor",
    category: "premium_depth",
    module: "premium",
    priority: 82,
    kind: "text",
    question: "Complete this sentence: I feel most like myself when I am...",
    placeholder: "Write one honest sentence",
  },
];

const TARGET_COUNTS = {
  core: 14,
  premium: 20,
  minimum: 10,
};

const CATEGORY_TARGETS = {
  demographic: 4,
  career_reality: 5,
  values: 4,
  psychology: 4,
  lifestyle: 3,
  premium_depth: 4,
};

module.exports = {
  BRANCH_THEMES,
  QUESTION_POOL,
  TARGET_COUNTS,
  CATEGORY_TARGETS,
};
